Respect react event handler
cyclejs/react pull request #13
Opened 2020-09-28 17:07 UTC by whitecolor

`@cycle/react` currenlty replaces react handler on the element with its own event handler, this probably should be changed and the existing handler should be respected and executed.

The case for this: sometimes react expect that the event handler to return a value (for example if to pass the event or something like this). So this PR checks if handler exists and executes it after cycle event handler.

Also added prettier config. If ok with this PR, probably need to check and set new formatting of other files as well.

@staltz

2020-09-28 19:40 UTC, staltz requested changes
Good PR, I think this change makes sense. I have one request, written inline.

Note, ideally the addition of prettier would be a separate PR (or at least separate commit), it's not good for codebase maintenance (e.g. using git blame) to have unrelated changes all together in one commit, **but** I don't mind merging it like this right now. So, no action needed from you, I'm just informing what's preferable for the next times.

2020-09-28 19:40 UTC, staltz commented on src/Incorporator.ts
> +      props[onFoo] = (ev: any) => {
Can you put the `if` condition outside of this arrow function? In the default case where we use the Cycle.js style without callbacks (the most common case when using cycle/react), we shouldn't wrap the handler function in an unnecessary function.

2020-09-29 06:47 UTC, whitecolor commented
Made PR with formatting https://github.com/cyclejs/react/pull/14 and then tried to rebase this PR, not sure if I did right with this PR, not very good at git =)

2020-09-29 08:11 UTC, staltz commented
The `if` change looks good. Now we just need this PR rebased or conflicts resolved, to merge. If you have difficulties rebasing, you can also open another branch/PR and `git cherry-pick` the commit.

2020-09-29 11:33 UTC, staltz approved these changes

2020-09-29 14:45 UTC, staltz commented
I suppose you're done and this is ready to merge?

2020-09-29 16:14 UTC, whitecolor commented
I believe yes, if not count a mess with commits.

2020-09-29 16:53 UTC, merged

2020-09-29 16:53 UTC, staltz commented
Thanks!

2020-09-29 19:23 UTC, staltz commented
Release 2.9.0